#
#   Copyright (C) 2014-2019 CASM Organization <https://casm-lang.org>
#   All rights reserved.
#
#   Developed by: Philipp Paulweber
#                 Emmanuel Pescosta
#                 <https://github.com/casm-lang/casm>
#
#   This file is part of casm.
#
#   casm is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   casm is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with casm. If not, see <http://www.gnu.org/licenses/>.
#

linux_task:
  container:
    image: casmlang/container.linux
    memory: 2
    cpu: 1
  env:
    GITHUB_TOKEN: ENCRYPTED[19dcafbe03141df9e8abdf355a77d2ab557d539e755543613a206894c44db3f7bcd7ab78d911c51b014bce5c0d46e929]
  matrix:
    env:
      B: "debug"
      C: "clang"
    env:
      B: "coverage"
      C: "gcc"
      CODECOV_TOKEN: ENCRYPTED[d8c9f79fb80e84a54de55ce49613507676cfabda0ad7f12220393fdba0499e048e6844074ca9e0d666d51133ec24c9bd]
  fetch_script:
    - make ci-fetch
  build_script:
    - make ci-build
  test_script:
    - make ci-test
  benchmark_script:
    - if [ "$B" == "release" ]; then make ci-benchmark; fi
  coverage_script:
    - |
      if [ "$C" == "gcc" ]; then
        wget https://codecov.io/bash;
        sh bash -f "!*#usr#include*" 2> /dev/null;
      fi

darwin_task:
  osx_instance:
    image: high-sierra-xcode-9.4.1
  env:
    GITHUB_TOKEN: ENCRYPTED[19dcafbe03141df9e8abdf355a77d2ab557d539e755543613a206894c44db3f7bcd7ab78d911c51b014bce5c0d46e929]
  matrix:
    env:
      B: "debug"
      C: "clang"
    env:
      B: "debug"
      C: "gcc"
  setup_script:
    - brew install cmake
    - if [ "$C" == "gcc" ]; then brew install gcc; fi
    - brew install flex  && brew link --force flex
    - brew install bison && brew link --force bison
  fetch_script:
    - make ci-fetch
  build_script:
    - make ci-build
  test_script:
    - make ci-test
  benchmark_script:
    - if [ "$B" == "release" ]; then make ci-benchmark; fi

windows_task:
  windows_container:
    image: casmlang/container.windows
    os_version: 2016
    cpu: 1
  env:
    GITHUB_TOKEN: ENCRYPTED[19dcafbe03141df9e8abdf355a77d2ab557d539e755543613a206894c44db3f7bcd7ab78d911c51b014bce5c0d46e929]
  matrix:
    env:
      V: mingw64
      B: "debug"
      C: "clang"
    env:
      V: mingw64
      B: "debug"
      C: "gcc"
  fetch_script:
    - set PATH=C:\msys2\%V%\bin;%PATH%
    - make ci-fetch
  build_script:
    - set PATH=C:\msys2\%V%\bin;%PATH%
    - make ci-build
  test_script:
    - set PATH=C:\msys2\%V%\bin;%PATH%
    - make ci-test
  benchmark_script:
    - set PATH=C:\msys2\%V%\bin;%PATH%
    - echo if "%B%"=="release" make ci-benchmark > obj\benchmark_script.bat
    - obj\benchmark_script.bat
