#
#   Copyright (C) 2014-2024 CASM Organization <https://casm-lang.org>
#   All rights reserved.
#
#   Developed by: Philipp Paulweber et al.
#   <https://github.com/casm-lang/casm/graphs/contributors>
#
#   This file is part of casm.
#
#   casm is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   casm is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with casm. If not, see <http://www.gnu.org/licenses/>.
#

{{active}}
{{public}}

---
resources:
{{resource:send-email}}
{{resource:after-midnight}}
{{resource:config}}

{{resource:casm-lang:libstdhl@master}}
{{resource:casm-lang:libpass@master}}
{{resource:casm-lang:libtptp@master}}

{{resource:casm-lang:libcasm-ir@master}}
{{resource:casm-lang:libcasm-rt@master}}
{{resource:casm-lang:libcasm-fe@master}}
{{resource:casm-lang:libcasm-tc@master}}

{{resource:casm-lang:casmi@master}}
{{resource:casm-lang:casmf@master}}
{{resource:casm-lang:casmd@master}}

{{resource:casm-lang:casm@master}}

jobs:
{{job:nightly:libstdhl@master}}
{{job:nightly:libpass@master}}
{{job:nightly:libtptp@master}}

{{job:nightly:libcasm-ir@master}}
{{job:nightly:libcasm-rt@master}}
{{job:nightly:libcasm-fe@master}}
{{job:nightly:libcasm-tc@master}}

{{job:nightly:casmi@master}}
{{job:nightly:casmf@master}}
{{job:nightly:casmd@master}}

{{job:nightly-nodeps:casm@master}}
