#
#   Copyright (C) 2014-2017 CASM Organization, https://casm-lang.org
#   All rights reserved.
#
#   Developed by: Philipp Paulweber
#                 Emmanuel Pescosta
#                 https://github.com/casm-lang/casm
#
#   This file is part of casm.
#
#   casm is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   casm is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with casm. If not, see <http://www.gnu.org/licenses/>.
#

---
resource_types:
# resource_type
  - name: email
    type: docker-image
    source:
      repository: mdomke/concourse-email-resource

# resource_type
  - name: status-github
    type: docker-image
    source:
      repository: dpb587/github-status-resource
      tag: master

# resource_type
  - name: git-branch-heads
    type: docker-image
    source:
      repository: vito/git-branch-heads-resource

# resource_type
  - name: status-travis
    type: docker-image
    source:
      repository: orangeopensource/travis-resource-image
      
resources:
# resource
  - name: send-email
    type: email
    source:
      from: casm-lang@casm-lang.org

# resource
  - name: libstdhl
    type: git
    source:
      uri: git@github.com:casm-lang/libstdhl.git
      private_key: {{github-auth}}
      disable_ci_skip: true

# resource
  - name: libstdhl-source-github
    type: git-branch-heads
    source:
      uri: git@github.com:casm-lang/libstdhl.git
      private_key: {{github-auth}}
      disable_ci_skip: true

# resource
  - name: libstdhl-status-github
    type: status-github
    source:
      repository: casm-lang/libstdhl
      github-token: {{github-token}}

# resource
  - name: libstdhl-status-travis
    type: status-travis
    source:
      repository: casm-lang/libstdhl
      github-token: {{github-token}}


jobs:
  - name: test-build-and-email
    plan:
    - aggregate:
      - get: libstdhl
        trigger: true
        params:
          version: every
          submodules: none
      - get: libstdhl-source-github
        trigger: true
        params:
          version: every
          submodules: none

    - task: do-your-build-task-here
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ppaulweber/docker-cpp
        inputs:
          - name: libstdhl
          - name: libstdhl-source-github
        run:
          path: sh
          args:
            - -exc
            - |
              ls -al ./*
              printenv
              git -C libstdhl branch
              git -C libstdhl describe --always --tags
              git -C libstdhl-source-github branch
              git -C libstdhl-source-github describe --always --tags

    - put: send-email
      params:
        to:
          - ppaulweber@gmail.com
        subject_text: |
          Test Subject
        body_text: |
          Test Body
          
  - name: test-status-travis
    plan:
    - aggregate:
      - get: libstdhl-status-travis
        trigger: true
        

    - task: do-your-build-task-here
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ppaulweber/docker-cpp
        inputs:
          - name: libstdhl-status-travis
        run:
          path: sh
          args:
            - -exc
            - |
              cat build-info.json

    - put: send-email
      params:
        to:
          - ppaulweber@gmail.com
        subject_text: |
          Test Subject
        body_text: |
          Test Body
          
  - name: test-status-github
    plan:
    - aggregate:
      - get: libstdhl-source-github
      - get: libstdhl-status-github

    - put: send-email
      params:
        to:
          - ppaulweber@gmail.com
        subject_text: |
          Test Subject
        body_text: |
          Test Body
